
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task-manager
  name: task-consumer
spec:
  selector:
    matchLabels:
      app: task-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: task-consumer
    spec:
      containers:
        - name: golang
          volumeMounts:
            - name: app-files
              mountPath: /app
          image: task-manager:latest
          imagePullPolicy: Never
          command: ["go", "run", "consumers/tasks_consumer.go"]
          env:
            - name: REDIS_URL
              value: redis:6379
      volumes:
        - name: app-files
          hostPath:
            path: /app
