apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-manager

resources:
  - namespace.yaml
  - mysql.yml
  - redis.yml
  - api.yml

generatorOptions:
  disableNameSuffixHash: true
