# Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: task-manager
  name: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379

---
# Service
kind: Service
apiVersion: v1
metadata:
  namespace: task-manager
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

